// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "BioGearsEquipment.hxx"

namespace mil
{
  namespace tatrc
  {
    namespace physiology
    {
      namespace datamodel
      {
        // BioGearsAnesthesiaMachineData
        // 

        const BioGearsAnesthesiaMachineData::Inhaling_type& BioGearsAnesthesiaMachineData::
        Inhaling () const
        {
          return this->Inhaling_.get ();
        }

        BioGearsAnesthesiaMachineData::Inhaling_type& BioGearsAnesthesiaMachineData::
        Inhaling ()
        {
          return this->Inhaling_.get ();
        }

        void BioGearsAnesthesiaMachineData::
        Inhaling (const Inhaling_type& x)
        {
          this->Inhaling_.set (x);
        }

        const BioGearsAnesthesiaMachineData::CurrentBreathingCycleTime_type& BioGearsAnesthesiaMachineData::
        CurrentBreathingCycleTime () const
        {
          return this->CurrentBreathingCycleTime_.get ();
        }

        BioGearsAnesthesiaMachineData::CurrentBreathingCycleTime_type& BioGearsAnesthesiaMachineData::
        CurrentBreathingCycleTime ()
        {
          return this->CurrentBreathingCycleTime_.get ();
        }

        void BioGearsAnesthesiaMachineData::
        CurrentBreathingCycleTime (const CurrentBreathingCycleTime_type& x)
        {
          this->CurrentBreathingCycleTime_.set (x);
        }

        void BioGearsAnesthesiaMachineData::
        CurrentBreathingCycleTime (::std::unique_ptr< CurrentBreathingCycleTime_type > x)
        {
          this->CurrentBreathingCycleTime_.set (std::move (x));
        }

        const BioGearsAnesthesiaMachineData::InspirationTime_type& BioGearsAnesthesiaMachineData::
        InspirationTime () const
        {
          return this->InspirationTime_.get ();
        }

        BioGearsAnesthesiaMachineData::InspirationTime_type& BioGearsAnesthesiaMachineData::
        InspirationTime ()
        {
          return this->InspirationTime_.get ();
        }

        void BioGearsAnesthesiaMachineData::
        InspirationTime (const InspirationTime_type& x)
        {
          this->InspirationTime_.set (x);
        }

        void BioGearsAnesthesiaMachineData::
        InspirationTime (::std::unique_ptr< InspirationTime_type > x)
        {
          this->InspirationTime_.set (std::move (x));
        }

        const BioGearsAnesthesiaMachineData::OxygenInletVolumeFraction_type& BioGearsAnesthesiaMachineData::
        OxygenInletVolumeFraction () const
        {
          return this->OxygenInletVolumeFraction_.get ();
        }

        BioGearsAnesthesiaMachineData::OxygenInletVolumeFraction_type& BioGearsAnesthesiaMachineData::
        OxygenInletVolumeFraction ()
        {
          return this->OxygenInletVolumeFraction_.get ();
        }

        void BioGearsAnesthesiaMachineData::
        OxygenInletVolumeFraction (const OxygenInletVolumeFraction_type& x)
        {
          this->OxygenInletVolumeFraction_.set (x);
        }

        void BioGearsAnesthesiaMachineData::
        OxygenInletVolumeFraction (::std::unique_ptr< OxygenInletVolumeFraction_type > x)
        {
          this->OxygenInletVolumeFraction_.set (std::move (x));
        }

        const BioGearsAnesthesiaMachineData::TotalBreathingCycleTime_type& BioGearsAnesthesiaMachineData::
        TotalBreathingCycleTime () const
        {
          return this->TotalBreathingCycleTime_.get ();
        }

        BioGearsAnesthesiaMachineData::TotalBreathingCycleTime_type& BioGearsAnesthesiaMachineData::
        TotalBreathingCycleTime ()
        {
          return this->TotalBreathingCycleTime_.get ();
        }

        void BioGearsAnesthesiaMachineData::
        TotalBreathingCycleTime (const TotalBreathingCycleTime_type& x)
        {
          this->TotalBreathingCycleTime_.set (x);
        }

        void BioGearsAnesthesiaMachineData::
        TotalBreathingCycleTime (::std::unique_ptr< TotalBreathingCycleTime_type > x)
        {
          this->TotalBreathingCycleTime_.set (std::move (x));
        }


        // BioGearsElectroCardioGramData
        // 

        const BioGearsElectroCardioGramData::HeartRythmTime_type& BioGearsElectroCardioGramData::
        HeartRythmTime () const
        {
          return this->HeartRythmTime_.get ();
        }

        BioGearsElectroCardioGramData::HeartRythmTime_type& BioGearsElectroCardioGramData::
        HeartRythmTime ()
        {
          return this->HeartRythmTime_.get ();
        }

        void BioGearsElectroCardioGramData::
        HeartRythmTime (const HeartRythmTime_type& x)
        {
          this->HeartRythmTime_.set (x);
        }

        void BioGearsElectroCardioGramData::
        HeartRythmTime (::std::unique_ptr< HeartRythmTime_type > x)
        {
          this->HeartRythmTime_.set (std::move (x));
        }

        const BioGearsElectroCardioGramData::HeartRythmPeriod_type& BioGearsElectroCardioGramData::
        HeartRythmPeriod () const
        {
          return this->HeartRythmPeriod_.get ();
        }

        BioGearsElectroCardioGramData::HeartRythmPeriod_type& BioGearsElectroCardioGramData::
        HeartRythmPeriod ()
        {
          return this->HeartRythmPeriod_.get ();
        }

        void BioGearsElectroCardioGramData::
        HeartRythmPeriod (const HeartRythmPeriod_type& x)
        {
          this->HeartRythmPeriod_.set (x);
        }

        void BioGearsElectroCardioGramData::
        HeartRythmPeriod (::std::unique_ptr< HeartRythmPeriod_type > x)
        {
          this->HeartRythmPeriod_.set (std::move (x));
        }

        const BioGearsElectroCardioGramData::Waveforms_type& BioGearsElectroCardioGramData::
        Waveforms () const
        {
          return this->Waveforms_.get ();
        }

        BioGearsElectroCardioGramData::Waveforms_type& BioGearsElectroCardioGramData::
        Waveforms ()
        {
          return this->Waveforms_.get ();
        }

        void BioGearsElectroCardioGramData::
        Waveforms (const Waveforms_type& x)
        {
          this->Waveforms_.set (x);
        }

        void BioGearsElectroCardioGramData::
        Waveforms (::std::unique_ptr< Waveforms_type > x)
        {
          this->Waveforms_.set (std::move (x));
        }


        // BioGearsInhalerData
        // 
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace mil
{
  namespace tatrc
  {
    namespace physiology
    {
      namespace datamodel
      {
        // BioGearsAnesthesiaMachineData
        //

        BioGearsAnesthesiaMachineData::
        BioGearsAnesthesiaMachineData ()
        : ::mil::tatrc::physiology::datamodel::AnesthesiaMachineData (),
          Inhaling_ (this),
          CurrentBreathingCycleTime_ (this),
          InspirationTime_ (this),
          OxygenInletVolumeFraction_ (this),
          TotalBreathingCycleTime_ (this)
        {
        }

        BioGearsAnesthesiaMachineData::
        BioGearsAnesthesiaMachineData (const Inhaling_type& Inhaling,
                                       const CurrentBreathingCycleTime_type& CurrentBreathingCycleTime,
                                       const InspirationTime_type& InspirationTime,
                                       const OxygenInletVolumeFraction_type& OxygenInletVolumeFraction,
                                       const TotalBreathingCycleTime_type& TotalBreathingCycleTime)
        : ::mil::tatrc::physiology::datamodel::AnesthesiaMachineData (),
          Inhaling_ (Inhaling, this),
          CurrentBreathingCycleTime_ (CurrentBreathingCycleTime, this),
          InspirationTime_ (InspirationTime, this),
          OxygenInletVolumeFraction_ (OxygenInletVolumeFraction, this),
          TotalBreathingCycleTime_ (TotalBreathingCycleTime, this)
        {
        }

        BioGearsAnesthesiaMachineData::
        BioGearsAnesthesiaMachineData (const Inhaling_type& Inhaling,
                                       ::std::unique_ptr< CurrentBreathingCycleTime_type > CurrentBreathingCycleTime,
                                       ::std::unique_ptr< InspirationTime_type > InspirationTime,
                                       ::std::unique_ptr< OxygenInletVolumeFraction_type > OxygenInletVolumeFraction,
                                       ::std::unique_ptr< TotalBreathingCycleTime_type > TotalBreathingCycleTime)
        : ::mil::tatrc::physiology::datamodel::AnesthesiaMachineData (),
          Inhaling_ (Inhaling, this),
          CurrentBreathingCycleTime_ (std::move (CurrentBreathingCycleTime), this),
          InspirationTime_ (std::move (InspirationTime), this),
          OxygenInletVolumeFraction_ (std::move (OxygenInletVolumeFraction), this),
          TotalBreathingCycleTime_ (std::move (TotalBreathingCycleTime), this)
        {
        }

        BioGearsAnesthesiaMachineData::
        BioGearsAnesthesiaMachineData (const BioGearsAnesthesiaMachineData& x,
                                       ::xml_schema::flags f,
                                       ::xml_schema::container* c)
        : ::mil::tatrc::physiology::datamodel::AnesthesiaMachineData (x, f, c),
          Inhaling_ (x.Inhaling_, f, this),
          CurrentBreathingCycleTime_ (x.CurrentBreathingCycleTime_, f, this),
          InspirationTime_ (x.InspirationTime_, f, this),
          OxygenInletVolumeFraction_ (x.OxygenInletVolumeFraction_, f, this),
          TotalBreathingCycleTime_ (x.TotalBreathingCycleTime_, f, this)
        {
        }

        BioGearsAnesthesiaMachineData::
        BioGearsAnesthesiaMachineData (const ::xercesc::DOMElement& e,
                                       ::xml_schema::flags f,
                                       ::xml_schema::container* c)
        : ::mil::tatrc::physiology::datamodel::AnesthesiaMachineData (e, f | ::xml_schema::flags::base, c),
          Inhaling_ (this),
          CurrentBreathingCycleTime_ (this),
          InspirationTime_ (this),
          OxygenInletVolumeFraction_ (this),
          TotalBreathingCycleTime_ (this)
        {
          if ((f & ::xml_schema::flags::base) == 0)
          {
            ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
            this->parse (p, f);
          }
        }

        void BioGearsAnesthesiaMachineData::
        parse (::xsd::cxx::xml::dom::parser< char >& p,
               ::xml_schema::flags f)
        {
          this->::mil::tatrc::physiology::datamodel::AnesthesiaMachineData::parse (p, f);

          for (; p.more_content (); p.next_content (false))
          {
            const ::xercesc::DOMElement& i (p.cur_element ());
            const ::xsd::cxx::xml::qualified_name< char > n (
              ::xsd::cxx::xml::dom::name< char > (i));

            // Inhaling
            //
            if (n.name () == "Inhaling" && n.namespace_ () == "uri:/mil/tatrc/physiology/datamodel")
            {
              if (!Inhaling_.present ())
              {
                this->Inhaling_.set (Inhaling_traits::create (i, f, this));
                continue;
              }
            }

            // CurrentBreathingCycleTime
            //
            {
              ::std::unique_ptr< ::xsd::cxx::tree::type > tmp (
                ::xsd::cxx::tree::type_factory_map_instance< 0, char > ().create (
                  "CurrentBreathingCycleTime",
                  "uri:/mil/tatrc/physiology/datamodel",
                  &::xsd::cxx::tree::factory_impl< CurrentBreathingCycleTime_type >,
                  false, true, i, n, f, this));

              if (tmp.get () != 0)
              {
                if (!CurrentBreathingCycleTime_.present ())
                {
                  ::std::unique_ptr< CurrentBreathingCycleTime_type > r (
                    dynamic_cast< CurrentBreathingCycleTime_type* > (tmp.get ()));

                  if (r.get ())
                    tmp.release ();
                  else
                    throw ::xsd::cxx::tree::not_derived< char > ();

                  this->CurrentBreathingCycleTime_.set (::std::move (r));
                  continue;
                }
              }
            }

            // InspirationTime
            //
            {
              ::std::unique_ptr< ::xsd::cxx::tree::type > tmp (
                ::xsd::cxx::tree::type_factory_map_instance< 0, char > ().create (
                  "InspirationTime",
                  "uri:/mil/tatrc/physiology/datamodel",
                  &::xsd::cxx::tree::factory_impl< InspirationTime_type >,
                  false, true, i, n, f, this));

              if (tmp.get () != 0)
              {
                if (!InspirationTime_.present ())
                {
                  ::std::unique_ptr< InspirationTime_type > r (
                    dynamic_cast< InspirationTime_type* > (tmp.get ()));

                  if (r.get ())
                    tmp.release ();
                  else
                    throw ::xsd::cxx::tree::not_derived< char > ();

                  this->InspirationTime_.set (::std::move (r));
                  continue;
                }
              }
            }

            // OxygenInletVolumeFraction
            //
            {
              ::std::unique_ptr< ::xsd::cxx::tree::type > tmp (
                ::xsd::cxx::tree::type_factory_map_instance< 0, char > ().create (
                  "OxygenInletVolumeFraction",
                  "uri:/mil/tatrc/physiology/datamodel",
                  &::xsd::cxx::tree::factory_impl< OxygenInletVolumeFraction_type >,
                  false, true, i, n, f, this));

              if (tmp.get () != 0)
              {
                if (!OxygenInletVolumeFraction_.present ())
                {
                  ::std::unique_ptr< OxygenInletVolumeFraction_type > r (
                    dynamic_cast< OxygenInletVolumeFraction_type* > (tmp.get ()));

                  if (r.get ())
                    tmp.release ();
                  else
                    throw ::xsd::cxx::tree::not_derived< char > ();

                  this->OxygenInletVolumeFraction_.set (::std::move (r));
                  continue;
                }
              }
            }

            // TotalBreathingCycleTime
            //
            {
              ::std::unique_ptr< ::xsd::cxx::tree::type > tmp (
                ::xsd::cxx::tree::type_factory_map_instance< 0, char > ().create (
                  "TotalBreathingCycleTime",
                  "uri:/mil/tatrc/physiology/datamodel",
                  &::xsd::cxx::tree::factory_impl< TotalBreathingCycleTime_type >,
                  false, true, i, n, f, this));

              if (tmp.get () != 0)
              {
                if (!TotalBreathingCycleTime_.present ())
                {
                  ::std::unique_ptr< TotalBreathingCycleTime_type > r (
                    dynamic_cast< TotalBreathingCycleTime_type* > (tmp.get ()));

                  if (r.get ())
                    tmp.release ();
                  else
                    throw ::xsd::cxx::tree::not_derived< char > ();

                  this->TotalBreathingCycleTime_.set (::std::move (r));
                  continue;
                }
              }
            }

            break;
          }

          if (!Inhaling_.present ())
          {
            throw ::xsd::cxx::tree::expected_element< char > (
              "Inhaling",
              "uri:/mil/tatrc/physiology/datamodel");
          }

          if (!CurrentBreathingCycleTime_.present ())
          {
            throw ::xsd::cxx::tree::expected_element< char > (
              "CurrentBreathingCycleTime",
              "uri:/mil/tatrc/physiology/datamodel");
          }

          if (!InspirationTime_.present ())
          {
            throw ::xsd::cxx::tree::expected_element< char > (
              "InspirationTime",
              "uri:/mil/tatrc/physiology/datamodel");
          }

          if (!OxygenInletVolumeFraction_.present ())
          {
            throw ::xsd::cxx::tree::expected_element< char > (
              "OxygenInletVolumeFraction",
              "uri:/mil/tatrc/physiology/datamodel");
          }

          if (!TotalBreathingCycleTime_.present ())
          {
            throw ::xsd::cxx::tree::expected_element< char > (
              "TotalBreathingCycleTime",
              "uri:/mil/tatrc/physiology/datamodel");
          }
        }

        BioGearsAnesthesiaMachineData* BioGearsAnesthesiaMachineData::
        _clone (::xml_schema::flags f,
                ::xml_schema::container* c) const
        {
          return new class BioGearsAnesthesiaMachineData (*this, f, c);
        }

        BioGearsAnesthesiaMachineData& BioGearsAnesthesiaMachineData::
        operator= (const BioGearsAnesthesiaMachineData& x)
        {
          if (this != &x)
          {
            static_cast< ::mil::tatrc::physiology::datamodel::AnesthesiaMachineData& > (*this) = x;
            this->Inhaling_ = x.Inhaling_;
            this->CurrentBreathingCycleTime_ = x.CurrentBreathingCycleTime_;
            this->InspirationTime_ = x.InspirationTime_;
            this->OxygenInletVolumeFraction_ = x.OxygenInletVolumeFraction_;
            this->TotalBreathingCycleTime_ = x.TotalBreathingCycleTime_;
          }

          return *this;
        }

        BioGearsAnesthesiaMachineData::
        ~BioGearsAnesthesiaMachineData ()
        {
        }

        static
        const ::xsd::cxx::tree::type_factory_initializer< 0, char, BioGearsAnesthesiaMachineData >
        _xsd_BioGearsAnesthesiaMachineData_type_factory_init (
          "BioGearsAnesthesiaMachineData",
          "uri:/mil/tatrc/physiology/datamodel");

        // BioGearsElectroCardioGramData
        //

        BioGearsElectroCardioGramData::
        BioGearsElectroCardioGramData ()
        : ::mil::tatrc::physiology::datamodel::ElectroCardioGramData (),
          HeartRythmTime_ (this),
          HeartRythmPeriod_ (this),
          Waveforms_ (this)
        {
        }

        BioGearsElectroCardioGramData::
        BioGearsElectroCardioGramData (const HeartRythmTime_type& HeartRythmTime,
                                       const HeartRythmPeriod_type& HeartRythmPeriod,
                                       const Waveforms_type& Waveforms)
        : ::mil::tatrc::physiology::datamodel::ElectroCardioGramData (),
          HeartRythmTime_ (HeartRythmTime, this),
          HeartRythmPeriod_ (HeartRythmPeriod, this),
          Waveforms_ (Waveforms, this)
        {
        }

        BioGearsElectroCardioGramData::
        BioGearsElectroCardioGramData (::std::unique_ptr< HeartRythmTime_type > HeartRythmTime,
                                       ::std::unique_ptr< HeartRythmPeriod_type > HeartRythmPeriod,
                                       ::std::unique_ptr< Waveforms_type > Waveforms)
        : ::mil::tatrc::physiology::datamodel::ElectroCardioGramData (),
          HeartRythmTime_ (std::move (HeartRythmTime), this),
          HeartRythmPeriod_ (std::move (HeartRythmPeriod), this),
          Waveforms_ (std::move (Waveforms), this)
        {
        }

        BioGearsElectroCardioGramData::
        BioGearsElectroCardioGramData (const BioGearsElectroCardioGramData& x,
                                       ::xml_schema::flags f,
                                       ::xml_schema::container* c)
        : ::mil::tatrc::physiology::datamodel::ElectroCardioGramData (x, f, c),
          HeartRythmTime_ (x.HeartRythmTime_, f, this),
          HeartRythmPeriod_ (x.HeartRythmPeriod_, f, this),
          Waveforms_ (x.Waveforms_, f, this)
        {
        }

        BioGearsElectroCardioGramData::
        BioGearsElectroCardioGramData (const ::xercesc::DOMElement& e,
                                       ::xml_schema::flags f,
                                       ::xml_schema::container* c)
        : ::mil::tatrc::physiology::datamodel::ElectroCardioGramData (e, f | ::xml_schema::flags::base, c),
          HeartRythmTime_ (this),
          HeartRythmPeriod_ (this),
          Waveforms_ (this)
        {
          if ((f & ::xml_schema::flags::base) == 0)
          {
            ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
            this->parse (p, f);
          }
        }

        void BioGearsElectroCardioGramData::
        parse (::xsd::cxx::xml::dom::parser< char >& p,
               ::xml_schema::flags f)
        {
          this->::mil::tatrc::physiology::datamodel::ElectroCardioGramData::parse (p, f);

          for (; p.more_content (); p.next_content (false))
          {
            const ::xercesc::DOMElement& i (p.cur_element ());
            const ::xsd::cxx::xml::qualified_name< char > n (
              ::xsd::cxx::xml::dom::name< char > (i));

            // HeartRythmTime
            //
            {
              ::std::unique_ptr< ::xsd::cxx::tree::type > tmp (
                ::xsd::cxx::tree::type_factory_map_instance< 0, char > ().create (
                  "HeartRythmTime",
                  "uri:/mil/tatrc/physiology/datamodel",
                  &::xsd::cxx::tree::factory_impl< HeartRythmTime_type >,
                  false, true, i, n, f, this));

              if (tmp.get () != 0)
              {
                if (!HeartRythmTime_.present ())
                {
                  ::std::unique_ptr< HeartRythmTime_type > r (
                    dynamic_cast< HeartRythmTime_type* > (tmp.get ()));

                  if (r.get ())
                    tmp.release ();
                  else
                    throw ::xsd::cxx::tree::not_derived< char > ();

                  this->HeartRythmTime_.set (::std::move (r));
                  continue;
                }
              }
            }

            // HeartRythmPeriod
            //
            {
              ::std::unique_ptr< ::xsd::cxx::tree::type > tmp (
                ::xsd::cxx::tree::type_factory_map_instance< 0, char > ().create (
                  "HeartRythmPeriod",
                  "uri:/mil/tatrc/physiology/datamodel",
                  &::xsd::cxx::tree::factory_impl< HeartRythmPeriod_type >,
                  false, true, i, n, f, this));

              if (tmp.get () != 0)
              {
                if (!HeartRythmPeriod_.present ())
                {
                  ::std::unique_ptr< HeartRythmPeriod_type > r (
                    dynamic_cast< HeartRythmPeriod_type* > (tmp.get ()));

                  if (r.get ())
                    tmp.release ();
                  else
                    throw ::xsd::cxx::tree::not_derived< char > ();

                  this->HeartRythmPeriod_.set (::std::move (r));
                  continue;
                }
              }
            }

            // Waveforms
            //
            {
              ::std::unique_ptr< ::xsd::cxx::tree::type > tmp (
                ::xsd::cxx::tree::type_factory_map_instance< 0, char > ().create (
                  "Waveforms",
                  "uri:/mil/tatrc/physiology/datamodel",
                  &::xsd::cxx::tree::factory_impl< Waveforms_type >,
                  false, true, i, n, f, this));

              if (tmp.get () != 0)
              {
                if (!Waveforms_.present ())
                {
                  ::std::unique_ptr< Waveforms_type > r (
                    dynamic_cast< Waveforms_type* > (tmp.get ()));

                  if (r.get ())
                    tmp.release ();
                  else
                    throw ::xsd::cxx::tree::not_derived< char > ();

                  this->Waveforms_.set (::std::move (r));
                  continue;
                }
              }
            }

            break;
          }

          if (!HeartRythmTime_.present ())
          {
            throw ::xsd::cxx::tree::expected_element< char > (
              "HeartRythmTime",
              "uri:/mil/tatrc/physiology/datamodel");
          }

          if (!HeartRythmPeriod_.present ())
          {
            throw ::xsd::cxx::tree::expected_element< char > (
              "HeartRythmPeriod",
              "uri:/mil/tatrc/physiology/datamodel");
          }

          if (!Waveforms_.present ())
          {
            throw ::xsd::cxx::tree::expected_element< char > (
              "Waveforms",
              "uri:/mil/tatrc/physiology/datamodel");
          }
        }

        BioGearsElectroCardioGramData* BioGearsElectroCardioGramData::
        _clone (::xml_schema::flags f,
                ::xml_schema::container* c) const
        {
          return new class BioGearsElectroCardioGramData (*this, f, c);
        }

        BioGearsElectroCardioGramData& BioGearsElectroCardioGramData::
        operator= (const BioGearsElectroCardioGramData& x)
        {
          if (this != &x)
          {
            static_cast< ::mil::tatrc::physiology::datamodel::ElectroCardioGramData& > (*this) = x;
            this->HeartRythmTime_ = x.HeartRythmTime_;
            this->HeartRythmPeriod_ = x.HeartRythmPeriod_;
            this->Waveforms_ = x.Waveforms_;
          }

          return *this;
        }

        BioGearsElectroCardioGramData::
        ~BioGearsElectroCardioGramData ()
        {
        }

        static
        const ::xsd::cxx::tree::type_factory_initializer< 0, char, BioGearsElectroCardioGramData >
        _xsd_BioGearsElectroCardioGramData_type_factory_init (
          "BioGearsElectroCardioGramData",
          "uri:/mil/tatrc/physiology/datamodel");

        // BioGearsInhalerData
        //

        BioGearsInhalerData::
        BioGearsInhalerData ()
        : ::mil::tatrc::physiology::datamodel::InhalerData ()
        {
        }

        BioGearsInhalerData::
        BioGearsInhalerData (const BioGearsInhalerData& x,
                             ::xml_schema::flags f,
                             ::xml_schema::container* c)
        : ::mil::tatrc::physiology::datamodel::InhalerData (x, f, c)
        {
        }

        BioGearsInhalerData::
        BioGearsInhalerData (const ::xercesc::DOMElement& e,
                             ::xml_schema::flags f,
                             ::xml_schema::container* c)
        : ::mil::tatrc::physiology::datamodel::InhalerData (e, f, c)
        {
        }

        BioGearsInhalerData* BioGearsInhalerData::
        _clone (::xml_schema::flags f,
                ::xml_schema::container* c) const
        {
          return new class BioGearsInhalerData (*this, f, c);
        }

        BioGearsInhalerData::
        ~BioGearsInhalerData ()
        {
        }

        static
        const ::xsd::cxx::tree::type_factory_initializer< 0, char, BioGearsInhalerData >
        _xsd_BioGearsInhalerData_type_factory_init (
          "BioGearsInhalerData",
          "uri:/mil/tatrc/physiology/datamodel");
      }
    }
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace mil
{
  namespace tatrc
  {
    namespace physiology
    {
      namespace datamodel
      {
        ::std::ostream&
        operator<< (::std::ostream& o, const BioGearsAnesthesiaMachineData& i)
        {
          o << static_cast< const ::mil::tatrc::physiology::datamodel::AnesthesiaMachineData& > (i);

          o << ::std::endl << "Inhaling: " << i.Inhaling ();
          {
            ::xsd::cxx::tree::std_ostream_map< char >& om (
              ::xsd::cxx::tree::std_ostream_map_instance< 0, char > ());

            o << ::std::endl << "CurrentBreathingCycleTime: ";
            om.insert (o, i.CurrentBreathingCycleTime ());
          }

          {
            ::xsd::cxx::tree::std_ostream_map< char >& om (
              ::xsd::cxx::tree::std_ostream_map_instance< 0, char > ());

            o << ::std::endl << "InspirationTime: ";
            om.insert (o, i.InspirationTime ());
          }

          {
            ::xsd::cxx::tree::std_ostream_map< char >& om (
              ::xsd::cxx::tree::std_ostream_map_instance< 0, char > ());

            o << ::std::endl << "OxygenInletVolumeFraction: ";
            om.insert (o, i.OxygenInletVolumeFraction ());
          }

          {
            ::xsd::cxx::tree::std_ostream_map< char >& om (
              ::xsd::cxx::tree::std_ostream_map_instance< 0, char > ());

            o << ::std::endl << "TotalBreathingCycleTime: ";
            om.insert (o, i.TotalBreathingCycleTime ());
          }

          return o;
        }

        static
        const ::xsd::cxx::tree::std_ostream_initializer< 0, char, BioGearsAnesthesiaMachineData >
        _xsd_BioGearsAnesthesiaMachineData_std_ostream_init;

        ::std::ostream&
        operator<< (::std::ostream& o, const BioGearsElectroCardioGramData& i)
        {
          o << static_cast< const ::mil::tatrc::physiology::datamodel::ElectroCardioGramData& > (i);

          {
            ::xsd::cxx::tree::std_ostream_map< char >& om (
              ::xsd::cxx::tree::std_ostream_map_instance< 0, char > ());

            o << ::std::endl << "HeartRythmTime: ";
            om.insert (o, i.HeartRythmTime ());
          }

          {
            ::xsd::cxx::tree::std_ostream_map< char >& om (
              ::xsd::cxx::tree::std_ostream_map_instance< 0, char > ());

            o << ::std::endl << "HeartRythmPeriod: ";
            om.insert (o, i.HeartRythmPeriod ());
          }

          {
            ::xsd::cxx::tree::std_ostream_map< char >& om (
              ::xsd::cxx::tree::std_ostream_map_instance< 0, char > ());

            o << ::std::endl << "Waveforms: ";
            om.insert (o, i.Waveforms ());
          }

          return o;
        }

        static
        const ::xsd::cxx::tree::std_ostream_initializer< 0, char, BioGearsElectroCardioGramData >
        _xsd_BioGearsElectroCardioGramData_std_ostream_init;

        ::std::ostream&
        operator<< (::std::ostream& o, const BioGearsInhalerData& i)
        {
          o << static_cast< const ::mil::tatrc::physiology::datamodel::InhalerData& > (i);

          return o;
        }

        static
        const ::xsd::cxx::tree::std_ostream_initializer< 0, char, BioGearsInhalerData >
        _xsd_BioGearsInhalerData_std_ostream_init;
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace mil
{
  namespace tatrc
  {
    namespace physiology
    {
      namespace datamodel
      {
      }
    }
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace mil
{
  namespace tatrc
  {
    namespace physiology
    {
      namespace datamodel
      {
        void
        operator<< (::xercesc::DOMElement& e, const BioGearsAnesthesiaMachineData& i)
        {
          e << static_cast< const ::mil::tatrc::physiology::datamodel::AnesthesiaMachineData& > (i);

          // Inhaling
          //
          {
            ::xercesc::DOMElement& s (
              ::xsd::cxx::xml::dom::create_element (
                "Inhaling",
                "uri:/mil/tatrc/physiology/datamodel",
                e));

            s << i.Inhaling ();
          }

          // CurrentBreathingCycleTime
          //
          {
            ::xsd::cxx::tree::type_serializer_map< char >& tsm (
              ::xsd::cxx::tree::type_serializer_map_instance< 0, char > ());

            const BioGearsAnesthesiaMachineData::CurrentBreathingCycleTime_type& x (i.CurrentBreathingCycleTime ());
            if (typeid (BioGearsAnesthesiaMachineData::CurrentBreathingCycleTime_type) == typeid (x))
            {
              ::xercesc::DOMElement& s (
                ::xsd::cxx::xml::dom::create_element (
                  "CurrentBreathingCycleTime",
                  "uri:/mil/tatrc/physiology/datamodel",
                  e));

              s << x;
            }
            else
              tsm.serialize (
                "CurrentBreathingCycleTime",
                "uri:/mil/tatrc/physiology/datamodel",
                false, true, e, x);
          }

          // InspirationTime
          //
          {
            ::xsd::cxx::tree::type_serializer_map< char >& tsm (
              ::xsd::cxx::tree::type_serializer_map_instance< 0, char > ());

            const BioGearsAnesthesiaMachineData::InspirationTime_type& x (i.InspirationTime ());
            if (typeid (BioGearsAnesthesiaMachineData::InspirationTime_type) == typeid (x))
            {
              ::xercesc::DOMElement& s (
                ::xsd::cxx::xml::dom::create_element (
                  "InspirationTime",
                  "uri:/mil/tatrc/physiology/datamodel",
                  e));

              s << x;
            }
            else
              tsm.serialize (
                "InspirationTime",
                "uri:/mil/tatrc/physiology/datamodel",
                false, true, e, x);
          }

          // OxygenInletVolumeFraction
          //
          {
            ::xsd::cxx::tree::type_serializer_map< char >& tsm (
              ::xsd::cxx::tree::type_serializer_map_instance< 0, char > ());

            const BioGearsAnesthesiaMachineData::OxygenInletVolumeFraction_type& x (i.OxygenInletVolumeFraction ());
            if (typeid (BioGearsAnesthesiaMachineData::OxygenInletVolumeFraction_type) == typeid (x))
            {
              ::xercesc::DOMElement& s (
                ::xsd::cxx::xml::dom::create_element (
                  "OxygenInletVolumeFraction",
                  "uri:/mil/tatrc/physiology/datamodel",
                  e));

              s << x;
            }
            else
              tsm.serialize (
                "OxygenInletVolumeFraction",
                "uri:/mil/tatrc/physiology/datamodel",
                false, true, e, x);
          }

          // TotalBreathingCycleTime
          //
          {
            ::xsd::cxx::tree::type_serializer_map< char >& tsm (
              ::xsd::cxx::tree::type_serializer_map_instance< 0, char > ());

            const BioGearsAnesthesiaMachineData::TotalBreathingCycleTime_type& x (i.TotalBreathingCycleTime ());
            if (typeid (BioGearsAnesthesiaMachineData::TotalBreathingCycleTime_type) == typeid (x))
            {
              ::xercesc::DOMElement& s (
                ::xsd::cxx::xml::dom::create_element (
                  "TotalBreathingCycleTime",
                  "uri:/mil/tatrc/physiology/datamodel",
                  e));

              s << x;
            }
            else
              tsm.serialize (
                "TotalBreathingCycleTime",
                "uri:/mil/tatrc/physiology/datamodel",
                false, true, e, x);
          }
        }

        static
        const ::xsd::cxx::tree::type_serializer_initializer< 0, char, BioGearsAnesthesiaMachineData >
        _xsd_BioGearsAnesthesiaMachineData_type_serializer_init (
          "BioGearsAnesthesiaMachineData",
          "uri:/mil/tatrc/physiology/datamodel");


        void
        operator<< (::xercesc::DOMElement& e, const BioGearsElectroCardioGramData& i)
        {
          e << static_cast< const ::mil::tatrc::physiology::datamodel::ElectroCardioGramData& > (i);

          // HeartRythmTime
          //
          {
            ::xsd::cxx::tree::type_serializer_map< char >& tsm (
              ::xsd::cxx::tree::type_serializer_map_instance< 0, char > ());

            const BioGearsElectroCardioGramData::HeartRythmTime_type& x (i.HeartRythmTime ());
            if (typeid (BioGearsElectroCardioGramData::HeartRythmTime_type) == typeid (x))
            {
              ::xercesc::DOMElement& s (
                ::xsd::cxx::xml::dom::create_element (
                  "HeartRythmTime",
                  "uri:/mil/tatrc/physiology/datamodel",
                  e));

              s << x;
            }
            else
              tsm.serialize (
                "HeartRythmTime",
                "uri:/mil/tatrc/physiology/datamodel",
                false, true, e, x);
          }

          // HeartRythmPeriod
          //
          {
            ::xsd::cxx::tree::type_serializer_map< char >& tsm (
              ::xsd::cxx::tree::type_serializer_map_instance< 0, char > ());

            const BioGearsElectroCardioGramData::HeartRythmPeriod_type& x (i.HeartRythmPeriod ());
            if (typeid (BioGearsElectroCardioGramData::HeartRythmPeriod_type) == typeid (x))
            {
              ::xercesc::DOMElement& s (
                ::xsd::cxx::xml::dom::create_element (
                  "HeartRythmPeriod",
                  "uri:/mil/tatrc/physiology/datamodel",
                  e));

              s << x;
            }
            else
              tsm.serialize (
                "HeartRythmPeriod",
                "uri:/mil/tatrc/physiology/datamodel",
                false, true, e, x);
          }

          // Waveforms
          //
          {
            ::xsd::cxx::tree::type_serializer_map< char >& tsm (
              ::xsd::cxx::tree::type_serializer_map_instance< 0, char > ());

            const BioGearsElectroCardioGramData::Waveforms_type& x (i.Waveforms ());
            if (typeid (BioGearsElectroCardioGramData::Waveforms_type) == typeid (x))
            {
              ::xercesc::DOMElement& s (
                ::xsd::cxx::xml::dom::create_element (
                  "Waveforms",
                  "uri:/mil/tatrc/physiology/datamodel",
                  e));

              s << x;
            }
            else
              tsm.serialize (
                "Waveforms",
                "uri:/mil/tatrc/physiology/datamodel",
                false, true, e, x);
          }
        }

        static
        const ::xsd::cxx::tree::type_serializer_initializer< 0, char, BioGearsElectroCardioGramData >
        _xsd_BioGearsElectroCardioGramData_type_serializer_init (
          "BioGearsElectroCardioGramData",
          "uri:/mil/tatrc/physiology/datamodel");


        void
        operator<< (::xercesc::DOMElement& e, const BioGearsInhalerData& i)
        {
          e << static_cast< const ::mil::tatrc::physiology::datamodel::InhalerData& > (i);
        }

        static
        const ::xsd::cxx::tree::type_serializer_initializer< 0, char, BioGearsInhalerData >
        _xsd_BioGearsInhalerData_type_serializer_init (
          "BioGearsInhalerData",
          "uri:/mil/tatrc/physiology/datamodel");
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

